/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.npaint.ui;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Huu Phuoc
 */
public final class ColoursPanel extends javax.swing.JPanel {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        color0Button = new javax.swing.JButton();
        color1Button = new javax.swing.JButton();
        color2Button = new javax.swing.JButton();
        color3Button = new javax.swing.JButton();
        color4Button = new javax.swing.JButton();
        color5Button = new javax.swing.JButton();
        color6Button = new javax.swing.JButton();
        color7Button = new javax.swing.JButton();
        color8Button = new javax.swing.JButton();
        color9Button = new javax.swing.JButton();
        color10Button = new javax.swing.JButton();
        color11Button = new javax.swing.JButton();
        color12Button = new javax.swing.JButton();
        color13Button = new javax.swing.JButton();
        color14Button = new javax.swing.JButton();
        color15Button = new javax.swing.JButton();
        color16Button = new javax.swing.JButton();
        color17Button = new javax.swing.JButton();
        color18Button = new javax.swing.JButton();
        color19Button = new javax.swing.JButton();
        color20Button = new javax.swing.JButton();
        colorLabel = new javax.swing.JLabel();
        colorChooserButton = new javax.swing.JButton();
        currentColorButton = new javax.swing.JButton();

        panel.setPreferredSize(new java.awt.Dimension(210, 90));
        panel.setLayout(new java.awt.GridLayout(3, 7));

        color0Button.setAlignmentY(0.0F);
        color0Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color0ButtonActionPerformed(evt);
            }
        });
        panel.add(color0Button);

        color1Button.setAlignmentY(0.0F);
        color1Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color1ButtonActionPerformed(evt);
            }
        });
        panel.add(color1Button);

        color2Button.setAlignmentY(0.0F);
        color2Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color2ButtonActionPerformed(evt);
            }
        });
        panel.add(color2Button);

        color3Button.setAlignmentY(0.0F);
        color3Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color3ButtonActionPerformed(evt);
            }
        });
        panel.add(color3Button);

        color4Button.setAlignmentY(0.0F);
        color4Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color4ButtonActionPerformed(evt);
            }
        });
        panel.add(color4Button);

        color5Button.setAlignmentY(0.0F);
        color5Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color5ButtonActionPerformed(evt);
            }
        });
        panel.add(color5Button);

        color6Button.setAlignmentY(0.0F);
        color6Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color6ButtonActionPerformed(evt);
            }
        });
        panel.add(color6Button);

        color7Button.setAlignmentY(0.0F);
        color7Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color7ButtonActionPerformed(evt);
            }
        });
        panel.add(color7Button);

        color8Button.setAlignmentY(0.0F);
        color8Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color8ButtonActionPerformed(evt);
            }
        });
        panel.add(color8Button);

        color9Button.setAlignmentY(0.0F);
        color9Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color9ButtonActionPerformed(evt);
            }
        });
        panel.add(color9Button);

        color10Button.setAlignmentY(0.0F);
        color10Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color10ButtonActionPerformed(evt);
            }
        });
        panel.add(color10Button);

        color11Button.setAlignmentY(0.0F);
        color11Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color11Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color11ButtonActionPerformed(evt);
            }
        });
        panel.add(color11Button);

        color12Button.setAlignmentY(0.0F);
        color12Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color12Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color12ButtonActionPerformed(evt);
            }
        });
        panel.add(color12Button);

        color13Button.setAlignmentY(0.0F);
        color13Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color13Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color13ButtonActionPerformed(evt);
            }
        });
        panel.add(color13Button);

        color14Button.setAlignmentY(0.0F);
        color14Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color14Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color14ButtonActionPerformed(evt);
            }
        });
        panel.add(color14Button);

        color15Button.setAlignmentY(0.0F);
        color15Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color15Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color15ButtonActionPerformed(evt);
            }
        });
        panel.add(color15Button);

        color16Button.setAlignmentY(0.0F);
        color16Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color16Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color16ButtonActionPerformed(evt);
            }
        });
        panel.add(color16Button);

        color17Button.setAlignmentY(0.0F);
        color17Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color17Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color17ButtonActionPerformed(evt);
            }
        });
        panel.add(color17Button);

        color18Button.setAlignmentY(0.0F);
        color18Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color18Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color18ButtonActionPerformed(evt);
            }
        });
        panel.add(color18Button);

        color19Button.setAlignmentY(0.0F);
        color19Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color19Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color19ButtonActionPerformed(evt);
            }
        });
        panel.add(color19Button);

        color20Button.setAlignmentY(0.0F);
        color20Button.setPreferredSize(new java.awt.Dimension(30, 30));
        color20Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color20ButtonActionPerformed(evt);
            }
        });
        panel.add(color20Button);

        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Colorous");
        colorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        colorChooserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/npaint/icon/color_chooser_icon.png"))); // NOI18N
        colorChooserButton.setText("Color");
        colorChooserButton.setToolTipText("Choose color");
        colorChooserButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorChooserButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        colorChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorChooserButtonActionPerformed(evt);
            }
        });

        currentColorButton.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(currentColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(colorChooserButton)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(currentColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorChooserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(colorLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorChooserButtonActionPerformed
        showColorChooser();
    }//GEN-LAST:event_colorChooserButtonActionPerformed

    private void color1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color1ButtonActionPerformed
        setCurrentColor(color1Button.getBackground());
    }//GEN-LAST:event_color1ButtonActionPerformed

    private void color2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color2ButtonActionPerformed
        setCurrentColor(color2Button.getBackground());
    }//GEN-LAST:event_color2ButtonActionPerformed

    private void color3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color3ButtonActionPerformed
        setCurrentColor(color3Button.getBackground());
    }//GEN-LAST:event_color3ButtonActionPerformed

    private void color4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color4ButtonActionPerformed
        setCurrentColor(color4Button.getBackground());
    }//GEN-LAST:event_color4ButtonActionPerformed

    private void color5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color5ButtonActionPerformed
        setCurrentColor(color5Button.getBackground());
    }//GEN-LAST:event_color5ButtonActionPerformed

    private void color6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color6ButtonActionPerformed
        setCurrentColor(color6Button.getBackground());
    }//GEN-LAST:event_color6ButtonActionPerformed

    private void color7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color7ButtonActionPerformed
        setCurrentColor(color7Button.getBackground());
    }//GEN-LAST:event_color7ButtonActionPerformed

    private void color8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color8ButtonActionPerformed
        setCurrentColor(color8Button.getBackground());
    }//GEN-LAST:event_color8ButtonActionPerformed

    private void color9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color9ButtonActionPerformed
        setCurrentColor(color9Button.getBackground());
    }//GEN-LAST:event_color9ButtonActionPerformed

    private void color10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color10ButtonActionPerformed
        setCurrentColor(color10Button.getBackground());
    }//GEN-LAST:event_color10ButtonActionPerformed

    private void color11ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color11ButtonActionPerformed
        setCurrentColor(color11Button.getBackground());
    }//GEN-LAST:event_color11ButtonActionPerformed

    private void color12ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color12ButtonActionPerformed
        setCurrentColor(color12Button.getBackground());
    }//GEN-LAST:event_color12ButtonActionPerformed

    private void color13ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color13ButtonActionPerformed
        setCurrentColor(color13Button.getBackground());
    }//GEN-LAST:event_color13ButtonActionPerformed

    private void color14ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color14ButtonActionPerformed
        setCurrentColor(color14Button.getBackground());
    }//GEN-LAST:event_color14ButtonActionPerformed

    private void color15ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color15ButtonActionPerformed
        setCurrentColor(color15Button.getBackground());
    }//GEN-LAST:event_color15ButtonActionPerformed

    private void color16ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color16ButtonActionPerformed
        setCurrentColor(color16Button.getBackground());
    }//GEN-LAST:event_color16ButtonActionPerformed

    private void color17ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color17ButtonActionPerformed
        setCurrentColor(color17Button.getBackground());
    }//GEN-LAST:event_color17ButtonActionPerformed

    private void color18ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color18ButtonActionPerformed
        setCurrentColor(color18Button.getBackground());
    }//GEN-LAST:event_color18ButtonActionPerformed

    private void color19ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color19ButtonActionPerformed
        setCurrentColor(color19Button.getBackground());
    }//GEN-LAST:event_color19ButtonActionPerformed

    private void color20ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color20ButtonActionPerformed
        setCurrentColor(color20Button.getBackground());
    }//GEN-LAST:event_color20ButtonActionPerformed

    private void color0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color0ButtonActionPerformed
        setCurrentColor(color0Button.getBackground());
    }//GEN-LAST:event_color0ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton color0Button;
    private javax.swing.JButton color10Button;
    private javax.swing.JButton color11Button;
    private javax.swing.JButton color12Button;
    private javax.swing.JButton color13Button;
    private javax.swing.JButton color14Button;
    private javax.swing.JButton color15Button;
    private javax.swing.JButton color16Button;
    private javax.swing.JButton color17Button;
    private javax.swing.JButton color18Button;
    private javax.swing.JButton color19Button;
    private javax.swing.JButton color1Button;
    private javax.swing.JButton color20Button;
    private javax.swing.JButton color2Button;
    private javax.swing.JButton color3Button;
    private javax.swing.JButton color4Button;
    private javax.swing.JButton color5Button;
    private javax.swing.JButton color6Button;
    private javax.swing.JButton color7Button;
    private javax.swing.JButton color8Button;
    private javax.swing.JButton color9Button;
    private javax.swing.JButton colorChooserButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton currentColorButton;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    private static Color currentColor;
    
    public ColoursPanel() {
        initComponents();
        initColorButton();
    }

    public void initColorButton() {
        Color[] colors = new Color[21];
        for (int i = 0; i < 21; i++) {
            colors[i] = Color.getHSBColor((float) i / (float) 21, 0.85f, 1.0f);
        }

        currentColorButton.setBackground(Color.BLACK);

        color0Button.setBackground(colors[0]);
        color1Button.setBackground(colors[1]);
        color2Button.setBackground(colors[2]);
        color3Button.setBackground(colors[3]);
        color4Button.setBackground(colors[4]);
        color5Button.setBackground(colors[5]);
        color6Button.setBackground(colors[6]);
        color7Button.setBackground(colors[7]);
        color8Button.setBackground(colors[8]);
        color9Button.setBackground(colors[9]);
        color10Button.setBackground(colors[10]);
        color11Button.setBackground(colors[11]);
        color12Button.setBackground(colors[12]);
        color13Button.setBackground(colors[13]);
        color14Button.setBackground(colors[14]);
        color15Button.setBackground(colors[15]);
        color16Button.setBackground(colors[16]);
        color17Button.setBackground(colors[17]);
        color18Button.setBackground(colors[18]);
        color19Button.setBackground(colors[19]);
        color20Button.setBackground(colors[20]);
    }

    public void showColorChooser() {
        Color brushColor = null;
        Color colorSelection = JColorChooser.showDialog(this, "Change Color", brushColor);
        if (colorSelection != null) {
            currentColorButton.setBackground(colorSelection);
        }
    }

    public void setCurrentColor(Color color) {
        currentColor = color;
        currentColorButton.setBackground(color);
    }
    
    public static Color getCurrentColor (){
        return currentColor;
    }
}
