/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.npaint.ui;

/**
 *
 * @author Huu Phuoc
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clipboardPanel = new com.npaint.ui.ClipboardPanel();
        imagePanel = new com.npaint.ui.ImagePanel();
        toolsPanel = new com.npaint.ui.ToolsPanel();
        brushesPanel = new com.npaint.ui.BrushesPanel();
        shapesPanel = new com.npaint.ui.ShapesPanel();
        sizePanel = new com.npaint.ui.SizePanel();
        coloursPanel = new com.npaint.ui.ColoursPanel();

        setPreferredSize(new java.awt.Dimension(1280, 200));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 8);
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);
        add(clipboardPanel);
        add(imagePanel);
        add(toolsPanel);
        add(brushesPanel);
        add(shapesPanel);
        add(sizePanel);
        add(coloursPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.npaint.ui.BrushesPanel brushesPanel;
    private com.npaint.ui.ClipboardPanel clipboardPanel;
    private com.npaint.ui.ColoursPanel coloursPanel;
    private com.npaint.ui.ImagePanel imagePanel;
    private com.npaint.ui.ShapesPanel shapesPanel;
    private com.npaint.ui.SizePanel sizePanel;
    private com.npaint.ui.ToolsPanel toolsPanel;
    // End of variables declaration//GEN-END:variables
}
