/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.npaint.ui;

import javax.swing.JComboBox;

/**
 *
 * @author Huu Phuoc
 */
public class SizePanel extends javax.swing.JPanel {

    /**
     * Creates new form BrushesPanel
     */
    public SizePanel() {
        initComponents();
        sizePanel = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeComboBox = new javax.swing.JComboBox<>();
        sizeChooserLabel = new javax.swing.JLabel();

        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Size 1", "Size 2", "Size 3", "Size 4", "Size 5", "Size 6" }));
        sizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeComboBoxActionPerformed(evt);
            }
        });

        sizeChooserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sizeChooserLabel.setText("Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sizeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sizeChooserLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(sizeChooserLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeComboBoxActionPerformed
        switch (sizeComboBox.getSelectedIndex()) {
            case 0:
                widthStroke = 3;
                break;
            case 1:
                widthStroke = 6;
                break;
            case 2:
                widthStroke = 9;
                break;
            case 3:
                widthStroke = 12;
                break;
            case 4:
                widthStroke = 15;
                break;
            case 5:
                widthStroke = 18;
                break;
            case 6:
                widthStroke = 21;
                break;
        }

        DrawingPanel.getDrawingPanel().setStroke(widthStroke);
    }//GEN-LAST:event_sizeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel sizeChooserLabel;
    private javax.swing.JComboBox<String> sizeComboBox;
    // End of variables declaration//GEN-END:variables

    private static SizePanel sizePanel;
    private static int widthStroke = 1;

    public static SizePanel getSizePanel() {
        return sizePanel;
    }

    public static int getWidthStroke() {
        return widthStroke;
    }

    public JComboBox<String> getSizeComboBox() {
        return sizeComboBox;
    }
    
    
}
