/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.npaint;

/**
 *
 * @author Huu Phuoc
 */
public class ColoursPanel extends javax.swing.JPanel {

    /**
     * Creates new form Colours
     */
    public ColoursPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        currentColorButton = new javax.swing.JButton();
        chooseColorButton = new javax.swing.JButton();
        colorLabel = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.GridLayout(3, 9));

        jButton3.setText("jButton1");
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton3);

        jButton4.setText("jButton3");
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton4);

        jButton5.setText("jButton5");
        jButton5.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton5);

        jButton6.setText("jButton2");
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton6);

        jButton7.setText("jButton4");
        jButton7.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton7);

        jButton8.setText("jButton6");
        jButton8.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton8);

        jButton9.setText("jButton1");
        jButton9.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton9);

        jButton10.setText("jButton3");
        jButton10.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton10);

        jButton11.setText("jButton5");
        jButton11.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton11);

        jButton12.setText("jButton2");
        jButton12.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton12);

        jButton13.setText("jButton4");
        jButton13.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton13);

        jButton14.setText("jButton6");
        jButton14.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton14);

        jButton15.setText("jButton1");
        jButton15.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton15);

        jButton16.setText("jButton3");
        jButton16.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton16);

        jButton17.setText("jButton5");
        jButton17.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton17);

        jButton21.setText("jButton1");
        jButton21.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton21);

        jButton22.setText("jButton3");
        jButton22.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton22);

        jButton23.setText("jButton5");
        jButton23.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton23);

        jButton28.setText("jButton5");
        jButton28.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton28);

        jButton29.setText("jButton5");
        jButton29.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton29);

        jButton27.setText("jButton6");
        jButton27.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton27);

        currentColorButton.setText("Color");

        chooseColorButton.setText("Color choose");

        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorLabel.setText("Colorous");
        colorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(currentColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooseColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseColorButton;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton currentColorButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
